version: '3.8'

services:
  back:
    build: .
    environment:
      # на случай, если .env лежит рядом с compose
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "${PORT}:3000"
