version: "3.7"
services:
  server:
    container_name: server
    build: ./server
    restart: always
    volumes:
    - ./src:/app/src
    ports:
      - "3011:3001"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_PORT: "${DB_PORT}"

